version: '3.8'
services:
  # PostgreSQL Database Service
  koi_db:
    image: postgres:13-alpine
    container_name: Postgres_DB
    environment:
      POSTGRES_DB: shop-koi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - koi-network

  # Redis Cache Service
  koi_redis:
    image: redis:6-alpine
    container_name: Redis_Cache
    ports:
      - "6379:6379"
    networks:
      - koi-network
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:

networks:
  koi-network:
